# -*- coding: utf-8 -*-
"""Untitled.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n1L9fFsAT9037U_LYfO-7sBrbDHX11Ja
"""

import numpy as np
import pandas as pd

dataset = pd.read_csv('UPI FRAUD DATASET/fraud_dataset.csv', index_col = 0)

dataset.head()

import numpy as np

x = dataset.iloc[:, :-1].values # all columns except last
y = dataset.iloc[:, -1].values # last column

import sklearn
!pip install sklearn

from sklearn.model_selection import train_test_split
x_train, x_test, y_train , y_test =train_test_split(x,y,test_size=0.15, random_state=0)

import numpy as np
import pandas as pd

dataset = pd.read_csv('/content/fraud_dataset.csv', index_col = 0)

x = dataset.iloc[:, :-1].values # all columns except last
y = dataset.iloc[:, -1].values # last column

from sklearn.model_selection import train_test_split
x_train, x_test, y_train , y_test =train_test_split(x,y,test_size=0.15, random_state=0)

x_train.shape

x_test.shape

fraud = np.count_nonzero(y_train == 1)
valid = np.count_nonzero(y_train == 0)

print('Fraud cases in training data =', fraud)
print('Valid cases in training data =', valid)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

import pandas as pd

# Create temporary DataFrames from the numpy arrays to easily select numeric columns
x_train_df = pd.DataFrame(x_train)
x_test_df = pd.DataFrame(x_test)

numeric_cols_indices = []
for i in range(x_train_df.shape[1]):
    # Attempt to convert column to numeric, coercing errors to NaN
    # If the column has at least one non-NaN value after coercion, it's considered numeric
    if pd.to_numeric(x_train_df[i], errors='coerce').notna().any():
        numeric_cols_indices.append(i)

# Select only the identified numeric columns
x_train = x_train_df[numeric_cols_indices].values
x_test = x_test_df[numeric_cols_indices].values

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

x_train[ : 5]

x_test[ : 5]

"""LOGISTIC REGRESSION(LR)"""

from sklearn.linear_model import LogisticRegression
LR_model = LogisticRegression()
LR_model.fit(x_train, y_train)

y_pred = LR_model.predict(x_test)

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)

acc_lr = accuracy_score(y_test, y_pred)
print('Accuracy of Logistic Regression Model =', acc_lr)

print(acc_lr)

"""K-NEAREST NEIGHBORS (KNN)"""

from sklearn.neighbors import KNeighborsClassifier
KNN_model = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
KNN_model.fit(x_train, y_train)

y_pred = KNN_model.predict(x_test)

acc_knn = accuracy_score(y_test, y_pred)
print('Accuracy of KNN Model =', acc_knn)

print(acc_knn)

"""SUPPORT VECTOR MECHINE(SVM)"""

from sklearn.svm import SVC
SVM_model = SVC(kernel = 'linear', random_state = 0)
SVM_model.fit(x_train, y_train)

y_pred = SVM_model.predict(x_test)

acc_svm = accuracy_score(y_test, y_pred)

print(acc_svm)

from sklearn.metrics import confusion_matrix, accuracy_score
cm_svm = confusion_matrix(y_test, y_pred)
print('Confusion Matrix for SVM Model:')
print(cm_svm)

print(acc_svm)

"""NAIVE BAYES (NB)"""

from sklearn.naive_bayes import GaussianNB
NB_model = GaussianNB()
NB_model.fit(x_train, y_train)

y_pred = NB_model.predict(x_test)

acc_nb = accuracy_score(y_test, y_pred)
print('Accuracy of Naive Bayes Model =', acc_nb)

"""DECISION TREE"""

from sklearn.ensemble import RandomForestClassifier
RF_model = RandomForestClassifier()
RF_model.fit(x_train, y_train)

y_pred = RF_model.predict(x_test)

acc_rfn = accuracy_score(y_test, y_pred)
print('Accuracy of Random Forest Model =', acc_rfn)

"""CONVOLUTIONAL NEURAL NETWORK (CNN)"""

import tensorflow as tf

CNN_model = tf.keras.models.Sequential()
CNN_model.add(tf.keras.layers.Dense(64, input_dim =x_train.shape[1], activation='relu'))
CNN_model.add(tf.keras.layers.Dense(128, activation = 'relu'))
CNN_model.add(tf.keras.layers.Dense(1, activation = 'sigmoid'))

CNN_model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

CNN_model.fit(x_train, y_train, batch_size = 32, epochs = 20)

loss, acc_cnn = CNN_model.evaluate(x_test, y_test, verbose =0)
print('Accuracy of CNN Model =', acc_cnn)

print(acc_cnn)

import numpy as np

y_pred_proba = CNN_model.predict(x_test)
# Convert probabilities to binary predictions based on the 0.5 threshold.
# Assuming the intent is: if probability > 0.5, classify as 0; else, classify as 1.
y_pred = np.where(y_pred_proba > 0.5, 0, 1)

"""ACCURACY COMPARISON OF ALL THE MODELS"""

scores = [acc_lr* 100,
          acc_knn* 100,
          acc_svm* 100,
          acc_nb * 100,
          acc_rfn * 100,
          acc_cnn * 100]

names = ['Logistic Regression',
         'K-Nearest Neighbors',
         'Support Vector Machine',
         'Naive Bayes',
         'Random Forest',
         'Convolutional Neural Network']

df = pd.DataFrame()
df['Algorithm Name'] =names
df['Accuracy Score (%)'] = scores
df = df.sort_values(by = 'Accuracy Score (%)', ascending = False)
df

import matplotlib.pyplot as plt
import seaborn as sns

fig = plt.subplots(figsize = (10, 5))
ax = sns.barplot(x = 'Algorithm Name', y = 'Accuracy Score (%)', data = df)

"""SAVING THE BEST TRAINED MODEL"""

import os.path

if os.path.isfile('../model/project_model1.h5') is False:
  CNN_model.save('../model/project_model1.h5')